In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm

In [2]:
feature1=pd.read_csv('Area10_100.csv')#第十次循环和第一百次循环的电压差之和
feature2=pd.read_csv('Area100_150.csv')#第十次循环和第一百次循环的电压差之和
label=pd.read_csv('Cycle_life.csv')#三个电池数据集的循环寿命



In [3]:
feature2.iloc[:,-1]

0      0.008169
1      0.008618
2      0.008344
3      0.010584
4      0.009057
         ...   
119    0.011697
120    0.011517
121    0.007465
122    0.008597
123    0.004812
Name: 0, Length: 124, dtype: float64

In [3]:
feature= pd.concat([feature1, feature2],axis=1)

In [6]:
import math

labellog=[]
for i in label.iloc[:,-1]:
    labellog.append(math.log(i,10))
    

featurelog=[]
for i in feature.iloc[:,-1]:
    featurelog.append(math.log(i,10))

In [4]:
from sklearn.preprocessing import MinMaxScaler
def normalization(data):

    scaler = MinMaxScaler()
    data=data.values   # 将pd的系列格式转换为np的数组格式
    data=scaler.fit_transform(np.array(data).reshape(-1,1))  #
    return data


feature1_scale=normalization(feature1.iloc[:,-1])
feature2_scale=normalization(feature2.iloc[:,-1])
label_scale=normalization(label.iloc[:,-1])


In [5]:
feature_scale= np.append(feature1_scale, feature2_scale, axis=1)
print(feature_scale.shape)

(124, 2)


In [9]:
#Spearman系数
import numpy as np
import pandas as pd
import scipy.stats as stats
def calculate_spearman_correlation(X, Y):
    r,p=stats.spearmanr(X, Y)
    return r,p

r,p=calculate_spearman_correlation(feature_scale,label_scale)
print("相关系数：",r)

# 使用面积的对特征和标签都没有进行处理的和都取对数的相关性一毛一样归一化也是
# 相关系数： -0.7842766999664926
#面积归一化：100-150循环：相关系数： -0.899444523235248

相关系数： [[ 1.          0.87932022 -0.7842767 ]
 [ 0.87932022  1.         -0.89944452]
 [-0.7842767  -0.89944452  1.        ]]


In [147]:
# #相关性分析相关系数
# from scipy.stats import pearsonr
# import numpy as np

# pc = pearsonr(feature_scale,label_scale)

# print("相关系数：",pc[0])
# print("显著性水平：",pc[1])
# #皮尔逊相关系数
# # 使用trapz方法求得面积HI和循环寿命相关性
# # 相关系数： -0.3330590845097132
# # 显著性水平： 0.00015699861600092712
# # 使用对label进行对数变换相关性
# # 相关系数： -0.4268528059239851
# # 显著性水平： 7.663700860852389e-07
# # 对feature和label都取对数
# # 相关系数： -0.7642849874683177
# # 显著性水平： 5.3514377043141e-25
# # mae:0.10048895463910852,rmse:0.14430292194504338
# # 只对feature取对数HI
# # 相关系数： -0.7396712673862962
# # 显著性水平： 1.0030562335241996e-22


# # 使用HI（sum）求得的结果
# # 两者都取对数
# # 相关系数： 0.4194667088183733
# # 显著性水平： 1.239259248417279e-06

In [6]:
from sklearn.model_selection import train_test_split

num=31
X_train,X_test=feature_scale[0:num,:],feature_scale[31:42,:]
y_train,y_test =np.array(label_scale).reshape(-1,1)[0:num,:],np.array(label_scale).reshape(-1,1)[31:42,:]
# train_data：所要划分的样本特征集
# train_target：所要划分的样本结果
# test_size：样本占比，如果是整数的话就是样本的数量
# random_state：是随机数的种子。
# 随机数种子：其实就是该组随机数的编号，在需要重复试验的时候，保证得到一组一样的随机数。比如你每次都填1，其他参数一样的情况下你得到的随机数组是一样的。但填0或不填，每次都会不一样。

In [7]:
print(X_train)
print(y_train)

[[0.         0.01342028]
 [0.00417013 0.01482458]
 [0.00427964 0.01396788]
 [0.01864538 0.02097338]
 [0.01199272 0.01619842]
 [0.0340648  0.01434635]
 [0.05412959 0.06285428]
 [0.05477569 0.04746682]
 [0.030182   0.03824051]
 [0.01611862 0.03363232]
 [0.029737   0.03268867]
 [0.02616351 0.03641303]
 [0.03286806 0.0321655 ]
 [0.02519535 0.03305487]
 [1.         0.09155641]
 [0.05777536 0.06194411]
 [0.15805012 0.15934552]
 [0.12885543 0.12414421]
 [0.04195582 0.0272229 ]
 [0.04005165 0.03398212]
 [0.03769138 0.03715685]
 [0.05863056 0.04823314]
 [0.05065619 0.04478185]
 [0.05368866 0.04356374]
 [0.05201984 0.04411339]
 [0.05901478 0.05759467]
 [0.06439636 0.05222903]
 [0.06710695 0.05934889]
 [0.07286379 0.06061164]
 [0.04832046 0.04023623]
 [0.05405468 0.04837053]]
[[0.81570129]
 [0.96314026]
 [1.        ]
 [0.61560555]
 [0.74724749]
 [0.44327429]
 [0.2336046 ]
 [0.34561991]
 [0.43370034]
 [0.30636668]
 [0.35040689]
 [0.27333652]
 [0.34179033]
 [0.33939684]
 [0.25993298]
 [0.30636668]


In [12]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
import xgboost as xgb


# model1=svm.SVR()
# model1.fit(X_train,y_train)
# y_pred=model1.predict(X_test)

# lr=LinearRegression().fit(X_train,y_train)
# y_pred=lr.predict(X_test)


xgb = xgb.XGBRegressor()
xgb.fit(X_train, y_train)
y_pred=xgb.predict(X_test)




In [13]:
from math import sqrt
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error


def evaluation(y_test, y_predict):
    mae = mean_absolute_error(y_test, y_predict)
    mse = mean_squared_error(y_test, y_predict)
    rmse = sqrt(mean_squared_error(y_test, y_predict))
    return mae, rmse

mae,rmse=evaluation(y_test, y_pred)
print('mae:{},rmse:{}'.format(mae,rmse))

mae:0.04316952009208106,rmse:0.056111260204743885


In [ ]:
#取对数
# 线性回归模型:
# mae:0.08575466092804905,rmse:0.09938170907406266
# SVR模型:
# mae:0.10048895463910852,rmse:0.14430292194504338


# 归一化
# 线性模型：
# mae:0.14554254643808506,rmse:0.15959797490667044
#100-150：mae:0.17576245618656097,rmse:0.35135613328270143
# SVR模型:
# 10-100：mae:0.05551163344347185,rmse:0.10401392864832236
#100-150：mae:0.10294093245641811,rmse:0.1406126182119327
#使用两个特征的结果 mae:0.07528818796971945,rmse:0.1334187348245085
#SVR对异常值比较敏感
# XGB模型：
#mae:0.04316952009208106,rmse:0.056111260204743885,两个特征都用

In [100]:
# print(y_pred)
# print(y_test)